### ISSUE TITLE
add support for gungames events

### ISSUE THREAD

**Issue by Drek282** [Drek282/ps_gungames#1]
Originally submitted by @bobl61

gg_win +10
gg_leader +1
gg_levelup +1
gg_leveldown -1
gg_knife_steal +2
gg_knife_level +1
gg_triple_level +3
gg_last_level +1

Not sure these 2 are not even relevant...
gg_team_win +5
gg_team_lose -5

**Comment by Rosenstein** [comment]
There is also:
gg_lose

Include gg_team_win, gg_team_lose just for the lols 😊

**Comment by Drek282** [comment]
that event is ignored because it is included in the gg_win event

**Comment by Drek282** [comment]
This has been done.
